---
name: Keep in sync with astronomer/main
on:  # yamllint disable-line rule:truthy
  # push:
  #   branches: [ main ]
  schedule:
    # TODO: Remove once this is working
    #        day of week  *: Each day of the week
    #                  |
    #            month |  *: Each month
    #                | |
    #   day of month | |  *: Each day of the month
    #              | | |
    #        hours | | |  *: Each hour
    #            | | | |
    #    minutes | | | |  */5: Every 5 minutes
    #          | | | | |
    #          v v v v v
    - cron: "*/5 * * * *"  # Run every 5 minutes every day
    # #      day of week  *: Each day of the week
    # #                |
    # #          month |  *: Each month
    # #              | |
    # # day of month | |  *: Each day of the month
    # #            | | |
    # #      hours | | |  0: 12am (UTC)
    # #          | | | |
    # #  minutes | | | |  0: :00
    # #        | | | | |
    # #        v v v v v
    # - cron: "0 0 * * *"  # Run every night at midnight UTC
jobs:
  sync-upstream:
    runs-on: ubuntu-20.04
    env:
      PAT: ${{ secrets.GH_PAT }}
    strategy:
      matrix:
        branch:
          - astro-main
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: astro-main
      - name: Rebase ${{ matrix.branch }}
        env:
          UPSTREAM_REPO: astronomer/airflow
          SOURCE_BRANCH: origin/main  # Always pull/rebase on to main
          DESTINATION_BRANCH: ${{ matrix.branch }}
        run: |
          set -eux -o pipefail

          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${PAT}@github.com/${GITHUB_REPOSITORY}"

          git fetch --all
          git rebase "${SOURCE_BRANCH}"
          git push --force origin "${DESTINATION_BRANCH}"
          git remote -v

  build-python-packages:
    timeout-minutes: 10
    name: "Publish wheels"
    runs-on: ubuntu-latest
    env:
      PULL_PYTHON_BASE_IMAGES_FROM_CACHE: "false"
      PYTHON_MAJOR_MINOR_VERSION: ${{ matrix.python-version }}
      CI_JOB_TYPE: "QA image"
      INSTALL_PROVIDERS_FROM_SOURCES: false
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'  # Will need to update this as Airflow advances
      - run: |
          pip install --upgrade pip==21.2.4
          pip install packaging GitPython wheel
      - name: Create Python Wheel
        run: ./scripts/ci/astronomer-qa-weekly-build.sh

        # - name: "Deploy Python Wheel and tar.gz"
        #   uses: actions-hub/gcloud@330.0.0
        #   env:
        #     APPLICATION_CREDENTIALS: ${{secrets.ASTRONOMER_PROD}}
        #     PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
        #   with:
        #     args: cp -a public-read -r ./dist/* gs://pip.astronomer.io/simple
        #     cli: gsutil
        # - name: "Deploy '.build' file (containing deployed version number)"
        #   uses: actions-hub/gcloud@330.0.0
        #   env:
        #     APPLICATION_CREDENTIALS: ${{secrets.ASTRONOMER_PROD}}
        #     PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
        #   with:
        #     args: >
        #       -h "Cache-Control:no-cache,max-age=0"
        #       cp -a public-read -r "./**/*.build" gs://pip.astronomer.io/simple/astronomer-certified
        #     cli: gsutil
        # - name: Index Pages
        #   env:
        #     GOOGLE_APPLICATION_CREDENTIALS_CONTENT: ${{secrets.ASTRONOMER_PROD}}
        #   run: |
        #     git clone https://github.com/astronomer/pip-release-utilities.git pip-release-utilities
        #     ./pip-release-utilities/build-index-page.sh pip.astronomer.io simple/apache-airflow
        #     ./pip-release-utilities/build-index-page.sh pip.astronomer.io simple/astronomer-certified
